[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = [
    'ds-test/=lib/ds-test/src/',
    '@superfluid-finance/=node_modules/@superfluid-finance/',
    '@openzeppelin/=node_modules/@openzeppelin/',
    '@chainlink/=node_modules/@chainlink',
]
# See more config options https://github.com/gakonst/foundry/tree/master/config
